import type { Metadata } from "next";
import ClientComponents from "./ClientComponents";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <ClientComponents>{children}</ClientComponents>
    );
}


 
 